services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: taskpulse-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # micro-services
  task-service:
    build:
      context: services/task-service
      dockerfile: Dockerfile
    env_file:
      - ./services/task-service/.env
    container_name: task-service
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    
  auth-service:
    build:
      context: services/auth-service
      dockerfile: Dockerfile
    env_file:
      - ./services/auth-service/.env
    container_name: auth-service
    ports:
      - "5003:5003"
    depends_on:
      - postgres
    command: sh -c "npx prisma db push --url \"$$DATABASE_URL\" && node dist/index.js"
volumes:
  pgdata:
  mongo-data: