name: Auth Service CI

on:
  push:
    branches: [main]
    paths:
      - 'services/auth-service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/auth-service
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'services/auth-service/package-lock.json'
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Vitest Integration test
        run: npm run test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook (upkri)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL}}